language: node_js
node_js:
  - "9"
before_script:
  - npm run build
after_script:
  - npm run commit-publish
deploy:
  api_key: "jmgaXwqqXDZMWdd7kj9zsckfkEDx6l+i/m2XZdi4nf2cr5vgKBQfQEEWO1Xu9CRoAsdlmXfiIivGKhC88xWKBSDl12HiQA52JQNZiQG+H7gx7iTAMglEAeBCISKy7gFOL+KHkHJzya4xDEWZqDFbhDk+uRoPx5akboTY52EnPT1wL+GhTyKSgCAvccmlUg1PwM62Cw8xmJkMGk/NjIuZzpn5by6W6pBIkZmsVSa+Z19RY/7h4UGAcUhFs/3YOA95GYNVGTFb8uaE1rE8eEkyM4OP6VEAV9DLVuCGW7aop+WJQzRMDtzWPvZKgfvYc/Hv/+TdPwmoaO00+zCVKQZFqZwF/E92CLC36TIhk9oK7Hl00R+X9ehHoDXgi09okYTkpO1WqxO5GKpCB5p1homNmHF0IKHYnYUqDr9YmvOeo9ktZjhcpoHGa34CnPv8pYRUwaZ8Z8EBKPFi86XUwU1XryhXFuWsaUXnAW1eliP/HQYVv9jlK1n3lxcZ7t7SliqCW3h9hsFZBpP3gmgJwGIZb4RfoM1FfhbrKAnCPf3xgel6oKJIB2LbAc+/reDaagUmoAqx8bngsPLwM1OnZgxWoTKsEoP/Isnfp3dMMy/t8+LhMt6gqPxsYzD+agMibzkALIfVuypmAEIl9/K40rpY+Z3Vspu1IY5AQwKydmqxXco="
  email: "compulim@hotmail.com"
  on:
    branch: master
  provider: npm
  skip_cleanup: true
  tag: master
