language: node_js
node_js:
  - "9"
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "PFK8ymADfH40ZAxPrgEwIJjueGyd5e7Tzm53jTpjp678hf5EgF/JlVt8yjJag2mLXvWeHFcO1BjfxGpAomiNBqhf6qnRHVxwaz2tcj/dWImN8BMMrmUcCe5bE4qucWXknj8QzQ30r+VAiLVUCsmn8QhY2I3ihiwbbCYb0QwfIRaagZy5Z0cafSlAVV376XGgxhBDMJlZ136Y2Pz9fYVXGdVyjzUMNF6JSbatSLazgy5Ain9sH2xga3NLItEIQuQEH5Dhj2B6AoVoHhIOrtcmTTkMvqCsfaI4mkU7kS0cdHxR7jLBBt+1N+ub4ujGDyscqCgCRtzcu4klJPK3k+PFjhl2OKgBKPFBMHhUWSEuEUina+cTi1lUjZ2kDZ8A5gp6AzNmoNfOzeyUSwgx+PjSg7Osh6nDRmubbV96lXQV/Ax9ve4hT4ocTq68LNP9wp/pme6lIa6J2dN6FfrdDSkjnwD1wMk6JaM5NEysx9DZvBI35jz+6F9P9PJ+7HG1HZ5aGkj2B/YxVpCzvgIq9MtiIHCJgQDf7XZGgMpiUb5mOKM7Dg9L4FRsLNrC5+T+1VmMBvmKgehAS+tQCajPfxrlmBuEMAXL3ZXPGdDwHad/yvFEOl6uv9LsSTfQdXnaWGrDswJiZEOWFowsYKNtHQxp/KljFsCECoiuW+D2PReu6vE="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "PFK8ymADfH40ZAxPrgEwIJjueGyd5e7Tzm53jTpjp678hf5EgF/JlVt8yjJag2mLXvWeHFcO1BjfxGpAomiNBqhf6qnRHVxwaz2tcj/dWImN8BMMrmUcCe5bE4qucWXknj8QzQ30r+VAiLVUCsmn8QhY2I3ihiwbbCYb0QwfIRaagZy5Z0cafSlAVV376XGgxhBDMJlZ136Y2Pz9fYVXGdVyjzUMNF6JSbatSLazgy5Ain9sH2xga3NLItEIQuQEH5Dhj2B6AoVoHhIOrtcmTTkMvqCsfaI4mkU7kS0cdHxR7jLBBt+1N+ub4ujGDyscqCgCRtzcu4klJPK3k+PFjhl2OKgBKPFBMHhUWSEuEUina+cTi1lUjZ2kDZ8A5gp6AzNmoNfOzeyUSwgx+PjSg7Osh6nDRmubbV96lXQV/Ax9ve4hT4ocTq68LNP9wp/pme6lIa6J2dN6FfrdDSkjnwD1wMk6JaM5NEysx9DZvBI35jz+6F9P9PJ+7HG1HZ5aGkj2B/YxVpCzvgIq9MtiIHCJgQDf7XZGgMpiUb5mOKM7Dg9L4FRsLNrC5+T+1VmMBvmKgehAS+tQCajPfxrlmBuEMAXL3ZXPGdDwHad/yvFEOl6uv9LsSTfQdXnaWGrDswJiZEOWFowsYKNtHQxp/KljFsCECoiuW+D2PReu6vE="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "MHeaFv2A/rfqMP3yTGS22WhWK9XVaH+d2oJa/gAtIvYm0wF4sX757Oz/SVmcXnsRPlk+1J0wGA17GPTh6aCYqQ3FOnbZiauFijQI/zjRuPepWilyjVkgwXiWgeRSkaTVfgBzbNRBmvdBf+Se7RnAdjfdJnErceXqqibMLvkqnSIWn2Tfw7GrRrhsBlOYVkNeehISBVUAPcRgpINwUgLEqzY/V3GOho91XKN3UUYr3q7JxC8/ChJfOMW0xiAz/FTM7NtynEL29mf14XcTxhKMY8nOxC8WDU2w/LECxfOV7BiX8m1Ylz/XYN+vyd1QLLnjlO9/KMouiDFpW3PHOKCrU1jcvz8sFw3CKSBFSIrW9JtlPwEcp9/myVP2tf73QbBjEy6RKIGlw+LHF4FjhVK1z0+F+s/Hcwuc3H+1fTif8jtxHUjnUbRpshlxmX1LuHwgZF46ntUzurlZEkn3Iod8XRERaDDn2ViwNaoCsM6W/MTyhXHPcRh04zb6CPydwL3zGe71T16Q41fwPwFo4mPgnFDcg8qMPjUCeck2lcVl7jJPPwZGdTzBK6WZsbze7ad+O3oO6yv/vZerFPk2BuNfoJkTYo2+U3BCX96ojeLxq+pwvWVIbOrqYkjyZEB0dgEHJ8y/Q8ZpgudpmocUJ4NIGIp09fxWleZb8x1LeZiwdUQ="
    on:
      tags: true
    skip_cleanup: true
